apiVersion: v1
kind: Secret
metadata:
  name: patient-management-secrets
  namespace: patient-management   # <-- always specify which namespace
type: Opaque                       # Opaque = generic key-value secret
data:
  # All values MUST be base64 encoded
  # To encode: echo -n "myvalue" | base64
  # To decode: echo "bXl2YWx1ZQ==" | base64 --decode

  JWT_SECRET: M2FhZDUyNWVlZDE5ZDk1NzNiYmUxZThlODhmNzhlOWY5ZDg2YzkxMWM2YmM3YzUxMThjZGFhZjM2OGQ1YjFmMzFjYzVhMGUyZTdiZTAzNzk1MmM4NDA2YzcyNzQ1M2ZiMzhlMTU0ZDYwZDE1MWU5OTQ5Yjk5N2UxMTdkYTM4MWE=

  # PostgreSQL passwords (both DBs use same password: "admin")
  POSTGRES_PASSWORD: YWRtaW4=
