version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: patient-service-db

    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5000:5432"

    volumes:
      - "C:/Users/joshi/Documents/Projects/Patient Management/db_volumes/patient-service-db:/var/lib/postgresql"

    networks:
      - internal

networks:
  internal:
    driver: bridge