spring.application.name=patient-service
server.port=4000


spring.datasource.url=jdbc:postgresql://localhost:5000/patient_db
spring.datasource.username=postgres
spring.datasource.password=admin


#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect.
spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=never
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC


#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#Kafka configuration:
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer