name: CI - All Services

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-patient-service:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: patient_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to mvnw
        run: chmod +x patient-service/mvnw

      - name: Build and test patient-service
        working-directory: patient-service
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/patient_db
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: admin
          SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
          BILLING_SERVICE_ADDRESS: localhost
          BILLING_SERVICE_GRPC_PORT: 9001
        run: ./mvnw clean package

  build-billing-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to mvnw
        run: chmod +x billing-service/mvnw

      - name: Build and test billing-service
        working-directory: billing-service
        run: ./mvnw clean package

  build-analytics-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to mvnw
        run: chmod +x analytics-service/mvnw

      - name: Build and test analytics-service
        working-directory: analytics-service
        env:
          SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
        run: ./mvnw clean package